### ISSUE TITLE
Raises exception under linux

### ISSUE THREAD

**Issue by cryoff** [ababak/OpenBash#1]
Hello! I am running fman under Ubuntu 16.04 (GUI: Xfce).

When trying to use OpenBash, i caught the following exception:
`Traceback (most recent call last):
  File "fman/impl/plugins/plugin.py", line 90, in _run_in_thread
  File "/home/mak/.config/fman/Plugins/Third-party/OpenBash/openbash/__init__.py", line 6, in __call__
    subprocess.call('C:/Program Files/Git/git-bash.exe --cd="{cd}"'.format(cd=self.pane.get_path()))
  File "subprocess.py", line 247, in call
  File "subprocess.py", line 676, in __init__
  File "subprocess.py", line 1282, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Program Files/Git/git-bash.exe --cd="/home/mak"'`

So, it is obvious that the path to bash is not linux-like :)

**Comment by ababak** [comment]
Yes, that's an expected behavior, as the readme says: "Windows only" :)
What do you want it to do on Linux? Open Terminal?

**Comment by cryoff** [comment]
Oops, haven't seen that :)
Yes, I would like it to open default terminal (whatever is bind in ubuntu) in the current folder

**Comment by ababak** [comment]
Fixed since version 1.3
